### ISSUE TITLE
ArgumentError when setting wrong type value to a column

### ISSUE THREAD

**Issue by teodor-pripoae** [cequel/cequel#126]
Hi,

I have the following setup:

``` ruby
class Rating
  include Cequel::Record
....
  key :id, :timeuuid, :auto => true
  column :value, :int

  validates_numericality_of :value
end
```

When I try: 

``` ruby
r = Rating.new(:value => "abc")
```

I get the following error:

```
ArgumentError: invalid value for Integer(): "abc"
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/type.rb:328:in `Integer'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/type.rb:328:in `cast'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/schema/column.rb:89:in `cast'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/persistence.rb:302:in `write_attribute'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/dirty.rb:62:in `write_attribute'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:210:in `value='
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:277:in `block in attributes='
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:276:in `each_pair'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:276:in `attributes='
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/mass_assignment.rb:39:in `attributes='
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:380:in `initialize_new_record'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/scoped.rb:62:in `initialize_new_record'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:55:in `block in new'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:54:in `tap'
    from /opt/boxen/rbenv/versions/2.1.2/gemsets/kuende/gems/cequel-1.3.2/lib/cequel/record/properties.rb:54:in `new'
    from (irb):17
```

I'm using ActiveModel validations to make sure `value` column will always be integer, and handle response if there is an error, instead of trying to catch the error.

What aproach do you suggest ? I do not want to make the check that `value` is integer inside the controller.

Later Edit: If I try Rating.new(:value => "123") it will set value 123 (integer) to the new instance.

**Comment by pezra** [comment]
I have encountered this, though it was relatively easy to work around. I agree that erroring on attribute assignment is a bug, since it goes against the ActiveModel norm. I'd merge a PR fix to this.
