### ISSUE TITLE
cequel/record/finders.rb:93: duplicated argument name

### ISSUE THREAD

**Issue by swistaczek** [cequel/cequel#206]
Hello,
I have recently tried **cequel 1.5.0**. First please take a look at my Cequel models:

``` ruby
class Account
  include Cequel::Record
  key :name, :text
  column :description, :text
  has_many :api_keys
end

class ApiKey
  include Cequel::Record
  belongs_to :account
  key :id, :timeuuid, auto: true
  column :secret, :text
end
```

After running `rake cequel:migrate`I recived following error:

``` ruby
SyntaxError: /Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/finders.rb:93: duplicated argument name
          def find_by_name_and_name(name, name)
                                              ^
/Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/finders.rb:90:in `def_finder'
/Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/finders.rb:75:in `def_key_finders'
/Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/finders.rb:61:in `key'
/Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/dirty.rb:22:in `key'
/Users/ernest.bursa/.rvm/gems/jruby-1.7.17@meta_store/bundler/gems/cequel-6935b245fef4/lib/cequel/record/timestamps.rb:36:in `key'
```

After small research I found that this error is rised due to #key_columns:

``` ruby
key_columns => [#<Cequel::Schema::PartitionKey: name text>, #<Cequel::Schema::ClusteringColumn: name text>]

method_suffix => "name_and_name
```

I have no expirence with Cequel and its internals, I would be very grateful if you could share any idea how to solve that issue.

**Comment by wflanagan** [comment]
So, this is "standard" behavior in rspec-preloader, which we use in our development workflow. It reloads any files that change. And, the consequence, we we get this error and can't use rspec-preloader.

**Comment by pezra** [comment]
That is unfortunate. I consider it a bug that loading the file more than once produces invalid finder methods. I'd merge a PR that fixed this bug.

**Comment by wflanagan** [comment]
@pezra Do you have thoughts on where I need to focus to fix this?

**Comment by wflanagan** [comment]
@pezra Following up no this. 

This gem is QUITE a mess in a docker-based development environment. Rspec tests don't seem to respect a YML file and expect 127.0.0.1 which is NOT the IP of a Cassandra server in a test environment in Docker.  This is making solving this problem exceedingly challenging.  

So much so that I am considering abandoning Cassandra all together for something more production worthy in a ruby context.  I truly worry that this repo/gem has not been updated in so long, that we'll be stuck waiting on updates related to Rails 5, docker, Rspec, and others.  

I do have my patch creating finders. But, the fixes cascade through the migrations and other areas of the system.. and i'm not pleased that my development on this feels like whack-a-mole. 

Some suggestions would be greatly appreciated, so I can deliver a pull request that has a shot at actually being merged.

**Comment by pezra** [comment]
I have been neglecting this project for the last few weeks because i was
overwhelmed at work. I think that has mostly settled down so hopefully I
will be able to merge some of the pending PRs real soon now.

Regarding your quality concerns, this is a volunteer project. We welcome
all improvements. There are many areas in which the code could be better
and there is no better person to make those improvments than you. I will
support you where i can.

Many people, including me, use cequel in production and it works rather
well but that does not mean that it is right for you. It is also worth
noting that cequel is not the only option for using Cassandra in ruby. If
you decide that cequel is not right for you please explore those other
options. However, if there is a viable alterative to Cassandra for your
problem you should seriously consider it. NoSQL databases are hard to use
well. Cassandra is no exception. If a relational database could possibly
work you will probably happier with it.

**Comment by wflanagan** [comment]
I understand that and appreciate where you are coming from. I think for me,
the core concern is that a code base is abandoned. If I spend a lot of time
hacking it to make it work, was it the right tool in the first place?

I spent more than a week on trying to make it work in our environment
(docker + rspec-preloader) and didn’t get there… so I gave up for now..
I’ll likely come back to it in a bit.. once my head heals from beating it
against the wall.. :-)

I appreciate the hard work and effort it requires to maintain an open
source project. I did not mean to diminish that.
