### ISSUE TITLE
Wrong number of arguments when running rake cequel:migrate

### ISSUE THREAD

**Issue by txdavidtx** [cequel/cequel#211]
Just started a new rails application. Completed each step without issue until `rake cequel:migrate`

I generated the rails app using `rails new some_application -O` to skip active record. Should I also exclude activemodel?

Here's the trace

```rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activemodel-4.2.0/lib/active_model/naming.rb:219:in `extended'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activemodel-4.2.0/lib/active_model/validations.rb:42:in `extend'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activemodel-4.2.0/lib/active_model/validations.rb:42:in `block in <module:Validations>'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `class_eval'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `append_features'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record/validations.rb:27:in `include'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record/validations.rb:27:in `block in <module:Validations>'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `class_eval'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `append_features'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record.rb:92:in `include'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record.rb:92:in `block in <module:Record>'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `class_eval'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `append_features'
/Users/davidhunt/readydevgo/webapps/chappy/app/models/user.rb:2:in `include'
/Users/davidhunt/readydevgo/webapps/chappy/app/models/user.rb:2:in `<class:User>'
/Users/davidhunt/readydevgo/webapps/chappy/app/models/user.rb:1:in `<top (required)>'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in `require_dependency'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record/tasks.rb:35:in `block (3 levels) in <top (required)>'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record/tasks.rb:29:in `each'
/Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/cequel-1.5.0/lib/cequel/record/tasks.rb:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => cequel:migrate```

Any ideas? Please :)

**Comment by txdavidtx** [comment]
Actually, this is likely related to issue #193 where the temporary solution is
```
module Forwardable
    remove_method :delegate
end
```
which I put in config/initializers/forwardable.rb
