### ISSUE TITLE
Broken test

### ISSUE THREAD

**Issue by olance** [cequel/cequel#230]
I just pulled cequel/master and tried to run the tests, but this one always fails:
(I'm testing with a 2.0.4 vagrant vm)

```
Failures:

  1) Cequel::Record::Finders secondary index should expose method to retrieve first result by secondary index
     Failure/Error: expect(Post.find_by_author_id(author_ids.first))
     Cassandra::Errors::NoHostsAvailable:
       All attempted hosts failed: 127.0.0.1 (Cassandra::Errors::ServerError: java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1))
     # ./lib/cequel/metal/keyspace.rb:193:in `block in execute_with_consistency'
     # ./lib/cequel/metal/request_logger.rb:34:in `block in log'
     # ./lib/cequel/metal/request_logger.rb:34:in `log'
     # ./lib/cequel/metal/keyspace.rb:191:in `execute_with_consistency'
     # ./lib/cequel/metal/data_set.rb:663:in `execute_cql'
     # ./lib/cequel/metal/data_set.rb:585:in `each'
     # ./lib/cequel/record/record_set.rb:714:in `entries'
     # ./lib/cequel/record/record_set.rb:714:in `find_rows_in_single_batch'
     # ./lib/cequel/record/record_set.rb:585:in `find_rows_in_batches'
     # ./lib/cequel/record/record_set.rb:569:in `find_each_row'
     # ./lib/cequel/record/record_set.rb:533:in `find_each'
     # ./lib/cequel/record/record_set.rb:478:in `each'
     # ./lib/cequel/record/record_set.rb:478:in `first'
     # ./lib/cequel/record/record_set.rb:478:in `first'
     # ./lib/cequel/record/finders.rb:87:in `find_by_author_id'
     # ./spec/examples/record/finders_spec.rb:173:in `block (3 levels) in <top (required)>'

Finished in 10.69 seconds (files took 1.93 seconds to load)
178 examples, 1 failure

Failed examples:

rspec ./spec/examples/record/finders_spec.rb:172 # Cequel::Record::Finders secondary index should expose method to retrieve first result by secondary index
```

I'm not sure what's to be done?

**Comment by olance** [comment]
Test passes with Cassandra 2.1.2

**Comment by pezra** [comment]
Closing since all tests pass with more modern versions of cassandra.
