### ISSUE TITLE
How can I do a 'greater than datetime' statement

### ISSUE THREAD

**Issue by joseronierison** [cequel/cequel#234]
How a do 
```ruby
MyModel.where('created_at > ?' => "2015-04-27 21:12:24") 
```
to build 
```sql
SELECT * FROM hits WHEREcreated_at > 1430179944000.
```

I tried too many ways, using this reference but it doesn't works. http://www.rubydoc.info/gems/cequel/1.5.0/Cequel/Metal/DataSet#where-instance_method

And reading more of documentation and code I found nothing about that.

Best regards.

**Comment by joseronierison** [comment]
I have tried with bettween so:

´´´ruby
my_model.where('created_at', Time.now-1.day..Time.now)
´´´

It builds a 'where statement' with the first time provided in range.

Regards.

**Comment by outoftime** [comment]
@joseronierison what are the keys/columns for that table? the good way to do this would be to use a UUID clustering column that encodes creation time, then do a timestamp range query

**Comment by joseronierison** [comment]
The structure is that:

```ruby
class Foo
  include Cequel::Record

  key :id, :timeuuid, auto: true

  column :user_token, :text
  column :title, :text
  column :mode, :text, default: :auto
  column :initial_date, :timestamp
  column :finish_date, :timestamp
  column :limit_access, :int
  column :progress_type, :text
  column :status, :text, default: :stoped
  column :selected_page, :text
  timestamps
end
```

I tried to use Foo.from(2.days.ago) for example, but it doesn't work as well.

When you say UUID clustering column, is that I do in this model? 
How do I a timestamp range query? I've searched in documentation and I've read the code but I didn't find.

Best regards.

**Comment by dayvsonlima** [comment]
up

**Comment by BrunoQuaresma** [comment]
up

**Comment by vitornogueira** [comment]
up

**Comment by outoftime** [comment]
@joseronierison The first key column specified is your partition key, and can't be used for ordering/range queries. Without knowing what a “Foo” actually is, I can't recommend anything specific, but it should be something that:

* Doesn't change
* Divides up your data evenly and with low cardinality

One good way to model this is using a [`belongs_to` relationship](https://github.com/cequel/cequel#compound-keys-and-parent-child-relationships). Using `belongs_to` implicitly defines a partition key column.

By default, the rest of the key columns that you define are your clustering columns. `id` should be a clustering column.

What you're specifying above is the right way to do a timestamp range query, you just need to have a partition key scoped, e.g.

```ruby
Foo.where(partition_key_name: 'partition_key_value').from(2.days.ago)
```

**Comment by Micka33** [comment]
@outoftime, @joseronierison 
I have almost the same question, *How to create a `smaller-than timestamp` statement*.  
I need to delete all datas that are older than a given date. It can be many days, many months, or many years of datas.  

Here is what my model looks like:

```
class Foos
  include Cequel::Record

  key :customer_id,          :bigint
  key :ending_period,        :timestamp,   { order: :desc }

  some columns here...
end
```

The following request works fine in cqlsh:
```
SELECT * FROM foos WHERE customer_id = 45583 AND ending_period < 1430863200000;
```

I tried the followings, but none worked:
```
irb(main):069:0* Cequel::Foos.where(customer_id: client_id).where(ending_period: " < #{today}")
CQL (2ms) SELECT * FROM foos WHERE customer_id = 45583 AND ending_period = 1430863200000 LIMIT 1000
=> []

irb(main):079:0> Cequel::Foos.where(customer_id: client_id).where("ending_period < #{today}")
NoMethodError: undefined method `symbolize_keys' for "ending_period < 2015-05-06":String
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/cequel-101b07cb8cdc/lib/cequel/record/record_set.rb:206:in `where'

irb(main):085:0* Cequel::Foos.where(customer_id: client_id).where("ending_period < ?" => today)
ArgumentError: No column ending_period < ? configured for Cequel::Foos
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/cequel-101b07cb8cdc/lib/cequel/record/record_set.rb:887:in `block in method_missing'

irb(main):087:0* Cequel::Foos.where(customer_id: client_id).where("ending_period < ?", today)
where(column_name, value) is deprecated. Use where(column_name => value) instead
ArgumentError: No column ending_period < ? configured for Cequel::Foos
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/cequel-101b07cb8cdc/lib/cequel/record/record_set.rb:887:in `block in method_missing'

```

**Comment by Micka33** [comment]
I achieved it this way :

```
irb(main):170:0> Cequel:: Foos.where(customer_id: client_id).where(ending_period: (today-100.years)...today).count
CQL (289ms) SELECT COUNT(*) FROM Foos WHERE customer_id = 45583 AND ending_period >= -1724889600000 AND ending_period < 1430863200000
=> 26507
irb(main):171:0>
```

I believe this is not the right way to do it, but it will work for now.

My new question now, is *How do I paginate this result ?*.  

Automatic paging has been implemented in the [cassandra 2.0 java driver](http://www.datastax.com/dev/blog/client-side-improvements-in-cassandra-2-0), is this possible this Cequel ?

**Comment by joseronierison** [comment]
Nice way, @Micka33 

Searching here in found this: http://docs.datastax.com/en/cql/3.0/cql/cql_using/paging_c.html

Regards
