### ISSUE TITLE
data_set_specs broken

### ISSUE THREAD

**Issue by muej** [cequel/cequel#239]
Hi there,

just checked out master and run tests against Cassandra 2.0.14 3 nodes cluster, which failed with:

```
Failures:

1) Cequel::Metal::DataSet#list_prepend should prepend multiple elements to list column
   Failure/Error: expect(cequel[:posts].where(row_keys).first[:categories]).to eq(

     expected: ["Partition Tolerance", "Scalability", "Big Data", "Cassandra"]
          got: ["Scalability", "Partition Tolerance", "Big Data", "Cassandra"]

     (compared using ==)
   # ./spec/examples/metal/data_set_spec.rb:199:in `block (3 levels) in <top (required)>'

2) Cequel::Record::List#unshift should atomically unshift
   Failure/Error: expect(subject[:tags]).to eq(%w(minustwo minusone zero one two))

     expected: ["minustwo", "minusone", "zero", "one", "two"]
          got: ["minusone", "minustwo", "zero", "one", "two"]

     (compared using ==)
   # ./spec/examples/record/list_spec.rb:429:in `block (3 levels) in <top (required)>'

3) Cequel::Record::List#unshift should persist unloaded unshift
   Failure/Error: expect(subject[:tags]).to eq(%w(minustwo minusone one two))

     expected: ["minustwo", "minusone", "one", "two"]
          got: ["minusone", "minustwo", "one", "two"]

     (compared using ==)
   # ./spec/examples/record/list_spec.rb:446:in `block (3 levels) in <top (required)>'

Finished in 12 minutes 58 seconds (files took 2.05 seconds to load)
797 examples, 3 failures, 1 pending

Failed examples:

rspec ./spec/examples/metal/data_set_spec.rb:194 # Cequel::Metal::DataSet#list_prepend should prepend multiple elements to list column
rspec ./spec/examples/record/list_spec.rb:425 # Cequel::Record::List#unshift should atomically unshift
rspec ./spec/examples/record/list_spec.rb:443 # Cequel::Record::List#unshift should persist unloaded unshift
```

**Comment by lesliev** [comment]
Cequel's tests assume the existence of a bug that was fixed in 2.1.3 and 2.0.13: https://issues.apache.org/jira/browse/CASSANDRA-8733
So the tests will break at and after those versions. 

@outoftime I'd like to fix these tests. Should they accept both list orders or should they attempt to detect the Cassandra version?

**Comment by lesliev** [comment]
I've made an attempt at fixing the tests and also optionally calling .reverse in List#unshift depending on the Cassandra version. I'll prepare a PR and someone can decide if its the right course of action.

**Comment by lesliev** [comment]
PR here: https://github.com/cequel/cequel/pull/252

**Comment by bernardofire** [comment]
Hi @muej.
Did @lesliev 's pull request and answer solved your issue ? 
Close it if so, please.

Regards,
Bernardo.

**Comment by pezra** [comment]
Closing due to age. Reopen if this is still a problem.
