### ISSUE TITLE
Cassandra::Errors::SyntaxError on cequel:migrate

### ISSUE THREAD

**Issue by rumblinthebronx** [cequel/cequel#260]
I am trying to use cequel with rails version 4.2.4 and Cassandra version 2.2.0. I also got the same error when i switched cassandra to version 2.1.11. I am using cequel 1.7.0. I am on ubuntu 14.04 64 bit.
```
  rake cequel:migrate --trace
** Invoke cequel:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute cequel:migrate
Synchronized schema for Activity
rake aborted!
Cassandra::Errors::SyntaxError: line 1:106 no viable alternative at input ')' (... text, PRIMARY KEY (([)]...)
/usr/local/lib/ruby/gems/2.2.0/gems/cassandra-driver-2.1.5/lib/cassandra/future.rb:570:in `get'
/usr/local/lib/ruby/gems/2.2.0/gems/cassandra-driver-2.1.5/lib/cassandra/future.rb:363:in `get'
/usr/local/lib/ruby/gems/2.2.0/gems/cassandra-driver-2.1.5/lib/cassandra/session.rb:121:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/cequel-1.7.0/lib/cequel/metal/keyspace.rb:205:in `block in execute_with_consistency'
```

Here are my models
```ruby
cat app/models/*

class Activity
  include Cequel::Record
  key :id, :timeuuid, auto: true
  column :user_id, :uuid 
  column :activity, :text, null: false
  column :subject_type, :text, null: false
  column :subject_id, :uuid, null: false
  column :model_type, :text
  column :model_id, :uuid
  column :organization_id, :uuid
  column :datetime, :timestamp
  column :model_name, :text
  column :subject_name, :text
 
  timestamps 
end

class Association
  include Cequel::Record
  column :associable_type, :text, null: false
  column :associable_id, :uuid
  column :name, :text, null: false
  column :value, :text, null: false
end

class Change
  include Cequel::Record
  key :id, :timeuuid, auto: true
  column :event, :text, null: false
  column :triggered_by, :uuid
  column :triggered_at, :uuid
  column :subject_id, :uuid, null: false
  column :subject_type, :text, null: false
  column :received_at, :timestamp
  
  before_save :set_received_at

  private

  def set_received_at
    self.received_at = Time.now
  end
end

```

Any insight would be helpful.

Thanks,
Sujin

**Comment by outoftime** [comment]
@rumblinthebronx heyo—looks like your Association class doesn’t have a key at all? Cassandra tables have to have at least one key column. Definitely Cequel should raise with a more descriptive error though.

**Comment by rumblinthebronx** [comment]
@outoftime thanks for the input.
