### ISSUE TITLE
Any where or find clause with more than 1000 items will fail with an exception

### ISSUE THREAD

**Issue by Geesu** [cequel/cequel#261]
I'm attempting to do a lookup to Cassandra where I have greater than 1000 keys.  Example:

`MyItem.where(the_key: keys).to_a`

This fails every single time with the following exception:

NoMethodError: undefined method `name' for nil:NilClass

Stack trace:
```0: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:796:in `range_key_name'
1: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:659:in `next_batch_from'
2: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:598:in `find_rows_in_batches'
3: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:569:in `find_each_row'
4: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:533:in `find_each'
5: /data/myapp/releases/20151117002754/vendor/bundle/ruby/2.2.0/bundler/gems/cequel-2803f748dcd4/lib/cequel/record/record_set.rb:517:in `each'```

**Comment by Geesu** [comment]
I added a failing spec to reproduce this: https://github.com/Geesu/cequel/commit/ff4d1106d270c890693a1201514e0f8151ab6ebf

**Comment by marktermaat** [comment]
I had the same problem, I think it's due to the fact that Cassandra uses 'limit 1000' by default. A temporary fix (for us) was to add '.limit(100000)' to the query (which we know will never reach that size).

**Comment by Geesu** [comment]
Have you noticed any issue with performance? We actually ended up doing this: 
https://gist.github.com/Geesu/36cbb67bedb194a19a48

For this use case we didn't need to worry about specifying the key as it was always the same.

**Comment by marktermaat** [comment]
Not really, because the size of the problem-query is about 2000 maximum, so not so large to cause performance issues.

**Comment by Looveh** [comment]
I've encountered the same problem on a collection size of ~30 000 records, where 
```ruby
MyModel.select(:column1, :column2).to_a 
```
throws 
```
Don't know how to cast nil to a UUID
```
but adding the `id` column to the select seems to solve the issue:
```ruby
MyModel.select(:id, :column1, :column2).to_a 
```
