### ISSUE TITLE
Is tests broken???

### ISSUE THREAD

**Issue by maxd** [cequel/cequel#264]
I run tests as recommended in [CONTRIBUTING.md](https://github.com/cequel/cequel/blob/master/CONTRIBUTING.md#for-the-impatient) but they pass with errors:

```
Run options:
  include {:focus=>true}
  exclude {:thrift=>true, :rails=>#<Proc:./spec/examples/spec_helper.rb:17>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 40357
...........*................................F...................................................................................................................................................................................FF...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...........................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Cequel::Schema::TableUpdater#drop_column should remove the column
     # Support in a future Cassandra version
     Failure/Error: drop_column :body

     NoMethodError:
       undefined method `drop_column' for #<Cequel::Schema::UpdateTableDSL:0x007fe6d63bae60>
     # ./spec/examples/schema/table_updater_spec.rb:150:in `block (4 levels) in <top (required)>'
     # ./lib/cequel/schema/update_table_dsl.rb:22:in `instance_eval'
     # ./lib/cequel/schema/update_table_dsl.rb:22:in `apply'
     # ./lib/cequel/schema/keyspace.rb:166:in `block in alter_table'
     # ./lib/cequel/schema/table_updater.rb:19:in `tap'
     # ./lib/cequel/schema/table_updater.rb:19:in `apply'
     # ./lib/cequel/schema/keyspace.rb:165:in `alter_table'
     # ./spec/examples/schema/table_updater_spec.rb:149:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:357:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:520:in `each'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:607:in `block in run_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:606:in `reverse_each'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:606:in `run_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:476:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:471:in `run_before_example'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:235:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'

Failures:

  1) Cequel::SpecSupport::Preparation keyspace doesn't exist causes #sync_schema to fail
     Failure/Error: expect{ prep.sync_schema }.to raise_error(Cassandra::Errors::InvalidError)
       expected Cassandra::Errors::InvalidError but nothing was raised
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `notify_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:87:in `to'
     # ./spec/examples/spec_support/preparation_spec.rb:62:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'

  2) Cequel::Record::List#unshift should persist unloaded unshift
     Failure/Error: expect(subject[:tags]).to eq(%w(minustwo minusone one two))

       expected: ["minustwo", "minusone", "one", "two"]
            got: ["minusone", "minustwo", "one", "two"]

       (compared using ==)
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `notify_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/examples/record/list_spec.rb:446:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'

  3) Cequel::Record::List#unshift should atomically unshift
     Failure/Error: expect(subject[:tags]).to eq(%w(minustwo minusone zero one two))

       expected: ["minustwo", "minusone", "zero", "one", "two"]
            got: ["minusone", "minustwo", "zero", "one", "two"]

       (compared using ==)
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `notify_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/examples/record/list_spec.rb:429:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'

  4) Cequel::Metal::DataSet#list_prepend should prepend multiple elements to list column
     Failure/Error:
       expect(cequel[:posts].where(row_keys).first[:categories]).to eq(
         ['Partition Tolerance', 'Scalability', 'Big Data', 'Cassandra']
       )

       expected: ["Partition Tolerance", "Scalability", "Big Data", "Cassandra"]
            got: ["Scalability", "Partition Tolerance", "Big Data", "Cassandra"]

       (compared using ==)
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `notify_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/examples/metal/data_set_spec.rb:199:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:544:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'

Finished in 2 minutes 32.5 seconds (files took 1.67 seconds to load)
801 examples, 4 failures, 1 pending

Failed examples:

rspec ./spec/examples/spec_support/preparation_spec.rb:61 # Cequel::SpecSupport::Preparation keyspace doesn't exist causes #sync_schema to fail
rspec ./spec/examples/record/list_spec.rb:443 # Cequel::Record::List#unshift should persist unloaded unshift
rspec ./spec/examples/record/list_spec.rb:425 # Cequel::Record::List#unshift should atomically unshift
rspec ./spec/examples/metal/data_set_spec.rb:194 # Cequel::Metal::DataSet#list_prepend should prepend multiple elements to list column

Randomized with seed 40357

```

Is it mean that some **released** Cequel functionality is broken? How does it can happen???

**Comment by outoftime** [comment]
@maxd unfortunately Cassandra makes small but breaking changes in patchlevel releases—these tests passed on latest Cassandra at the time they were written, but do not pass against the latest version (mostly having to do with the way collections are ordered).

**Comment by maxd** [comment]
Get it. As I understand need to update tests for compatibility with version 2.2.4 and 3.0.2 (or any latest versions) in the future. Right?
