### ISSUE TITLE
Unable to find class for belongs_to association

### ISSUE THREAD

**Issue by pranny** [cequel/cequel#291]
I am creating a standalone ruby gem that has models in it. It is a simple gem that provides Blog/Post example from the readme. The dir structure goes like

```bash
- blogger.gemspec
- lib/
    - blogger.rb
    - blogger/
        - models.rb
        - models/
        	  - blog.rb
        	  - post.rb
        
```
The contents are as follows:

**blog.rb**

```ruby
require 'cequel'

module Blogger::Core
  class Blog
    include Cequel::Record
    key :id, :uuid
    has_many :posts
  end
end

```

**post.rb**

```ruby
require 'cequel'
require 'blogger/models/blog'

module Blogger::Core
  class Post
    include Cequel::Record
    belongs_to :blog
    key :id, :bigint
    column :created_at, :timestamp
  end
end

```

Once I install this gem and require it in irb, I get the error

```ruby

require 'blogger'
NameError: uninitialized constant Blog
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/record/belongs_to_association.rb:45:in `association_class'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/record/associations.rb:117:in `belongs_to'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/blogger-0.0.1/lib/blogger/models/post.rb:9:in `<class:User>'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/blogger-0.0.1/lib/blogger/models/post.rb:6:in `<module:Core>'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/blogger-0.0.1/lib/blogger/models/post.rb:5:in `<top (required)>'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/blogger-0.0.1/lib/blogger/models.rb:2:in `<top (required)>'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/u1/.rvm/gems/ruby-2.1.5/gems/blogger-0.0.1/lib/blogger.rb:4:in `<top (required)>'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/u1/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1


```

It looks like it is unable to find the `Blog` class. I am not sure why this would happen, and have been trying a bunch of things with no success. What could be going wrong here?

**Comment by pranny** [comment]
So, it turns out that if I remove the module name from the model class definitions, this works great. This brings out the possibilities that only global class names are evaluated for `belongs_to` association. 

I even tried to have a association defined as `belongs_to 'Blogger::Blog'.to_sym` but of no use.

Is there any way to keep the models inside a module and yet be able to define associations between them or should they all be in global namespace?

**Comment by pranny** [comment]
Found the [PR](https://github.com/cequel/cequel/pull/98) that addresses this concern. I think it's good to edit the README.md to include documentation about this.
