### ISSUE TITLE
Unable to create schema

### ISSUE THREAD

**Issue by pranny** [cequel/cequel#293]
I am using Cequel without Rails (or Sinatra). It's a standalone gem. I tried to use `rake cequel:init` and it throws error:

```ruby
NoMethodError: undefined method `schema' for nil:NilClass
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/record/tasks.rb:38:in `create!'
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/record/tasks.rb:9:in `block (3 levels) in <top (required)>'
/Users/pranav/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pranav/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

It's originating maybe because I didn't specify any configuration file. So, this time I create a custom Rakefile that does the following

```ruby
config_file = 'lib/blogger/config/config.yml'
  config = YAML.load_file config_file
  Cequel.connect(config)
  Cequel::Record.establish_connection(config)
  Cequel::Record.connection.schema.create!
```

The **config.yaml** is below:

```yaml
name: blogger_development
host: '127.0.0.1'
port: 9042
keyspace: blogger_development
max_retries: 3
retry_delay: 0.5
replication:
  class: SimpleStrategy
  replication_factor: 1
```

However, this throws following error

```ruby
Cassandra::Errors::SyntaxError: line 2:0 no viable alternative at input 'WITH' (CREATE KEYSPACE [WITH]...)
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cassandra-driver-2.1.5/lib/cassandra/future.rb:570:in `get'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cassandra-driver-2.1.5/lib/cassandra/future.rb:363:in `get'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cassandra-driver-2.1.5/lib/cassandra/session.rb:121:in `execute'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/metal/keyspace.rb:205:in `block in execute_with_consistency'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/metal/request_logger.rb:30:in `log'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/metal/keyspace.rb:203:in `execute_with_consistency'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/metal/keyspace.rb:187:in `execute'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.7.0/lib/cequel/schema/keyspace.rb:75:in `create!'
```

What am i missing here?

**Comment by pranny** [comment]
So it turns out that I had to deep symbolise the keys from YAML before it could be useable. Spend hours on it like crazy. Here is how to do it:

```ruby
config_file = 'lib/blogger/config/config.yml'
  config = YAML.load(config_file).deep_symbolize_keys
  Cequel.connect(config)
  Cequel::Record.establish_connection(config)
  Cequel::Record.connection.schema.create!
```

If you're wondering how it occured to me, take a look at [this line](https://github.com/cequel/cequel/blob/master/lib/cequel/record/railtie.rb#L56)

**Comment by pranny** [comment]
Turns out that there is a better way to do this. Define your Rakefile as 

```ruby
require 'cequel'
require 'yaml'

task :environment do
  config_file = 'lib/octocore/config/config.yml'
  config = YAML.load_file(config_file).deep_symbolize_keys

  connection = Cequel.connect(config)
  Cequel::Record.connection = connection

end

spec = Gem::Specification.find_by_name 'cequel'
load "#{spec.gem_dir}/lib/cequel/record/tasks.rb"
```

**Comment by pezra** [comment]
Glad you found a solution.
