### ISSUE TITLE
Issue with Marshalling of set

### ISSUE THREAD

**Issue by pranny** [cequel/cequel#303]
I have a class and i use redis as a temp store. I use `Marshal::dump` when putting the record in redis and use `Marshal::load` when retrieving it back. The design looks like

```ruby
class Product
  include Cequel::Record
  key :id, :bigint
  set :categories, :text
end

module Utils
    class << self
      def serialize(record)
        Marshal::dump(record)
      end

      def deserialize(data)
        Marshal::load(data)
      end
    end
  end
```

And the actual way it happens is

```ruby
# setting
res = self.where(args)
Redis.setex(cache_key, ttl, Utils.serialize(res))

#getting
Utils.serialize( Redis.get(cache_key) )
```
It works great while setting, but while retrieving I get the error like below

```
E, [2016-06-06T13:33:49.690200 #15639] ERROR -- Octo: undefined method `fail' for #<Set: {"fk1", "fk2"}> (NoMethodError)
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.9.0/lib/cequel/record/collection.rb:127:in `__setobj__'
/Users/pranav/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/delegate.rb:191:in `marshal_load'
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.6/lib/active_support/core_ext/marshal.rb:6:in `load'
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.6/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/octocore-0.0.1/lib/octocore/utils.rb:19:in `deserialize'
```

It looks like it is trying to set the value of the "set" of categories but unable to do so because it is a read only object. Why would set be a read only object?

**Comment by pranny** [comment]
So after more investigation, I figured out that the issue arises only when any operation has been performed on the instance.

So the following works great
```ruby
p = Product.first
Marshal.load(Marsha.dump(p))
```

However, following throws the same error
```ruby
p = Product.first
p.categories
Marshal.load(Marsha.dump(p))
```

**Comment by pranny** [comment]
So i figured out that the issue is because of what `instance_variables` Marshal choose while marshalling.
In a normal scenerio, it would choose all of them which includes `[:@attributes, :@collection_proxies, :@loaded, :@persisted, :@record_collection, ....]`. However, for caching and retrieving purposes it looks like just the `attributes` are sufficient. 

So to resolve, i used following

```ruby
module Cequel
  module Record
     DUMP_ATTRS = [:@attributes]
      def marshal_dump
      DUMP_ATTRS.inject({}) do |val, attr|
        val[attr] = self.instance_variable_get(attr)
        val
      end
    end

    def marshal_load(data)
      DUMP_ATTRS.each do |attr|
        instance_variable_set(attr, data[attr])
      end
      instance_variable_set(:@collection_proxies, {})
      instance_variable_set(:@record_collection, nil)
    end
  end
end
```

and the serialising bit as
```ruby
      # Serialize one record before adding it to the cache. Creates a ruby byte
      #   stream
      # @param [Object] record Any object to be serialized
      def serialize(record)
        Marshal::dump(record).to_s
      end

      # Deserialize a data.
      # @param [String] data A string containing Marshal dump of the object
      def deserialize(data)
        Marshal::load(data)
      end
```

**Comment by pezra** [comment]
Glad you figured out the problem. Care to submit that change as PR?

**Comment by pranny** [comment]
Sure, I'd love to. I haven't noticed any issues with this so far. Would do it soon.
