### ISSUE TITLE
rake aborted on cequel:migrate for rails 5

### ISSUE THREAD

**Issue by jersten** [cequel/cequel#326]
Using Ruby 2.3 and rails 5; was playing around with cequel and ran into the following:

```
$ rake cequel:migrate --trace
** Invoke cequel:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute cequel:migrate
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/j/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/forwardable.rb:133:in `instance_delegate'
/home/j/.rvm/gems/ruby-2.3.0/gems/activemodel-5.0.0.1/lib/active_model/naming.rb:221:in `extended'
/home/j/.rvm/gems/ruby-2.3.0/gems/activemodel-5.0.0.1/lib/active_model/validations.rb:42:in `extend'
/home/j/.rvm/gems/ruby-2.3.0/gems/activemodel-5.0.0.1/lib/active_model/validations.rb:42:in `block in <module:Validations>'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record/validations.rb:27:in `include'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record/validations.rb:27:in `block in <module:Validations>'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record.rb:90:in `include'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record.rb:90:in `block in <module:Record>'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
/home/j/Desktop/.../app/models/metrics.rb:2:in `include'
/home/j/Desktop/.../app/models/metrics.rb:2:in `<class:Metric>'
/home/j/Desktop/.../app/models/metrics.rb:1:in `<top (required)>'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:477:in `load'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:477:in `block in load_file'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:476:in `load_file'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
/home/j/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record/tasks.rb:25:in `block (3 levels) in <top (required)>'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record/tasks.rb:22:in `each'
/home/j/.rvm/gems/ruby-2.3.0/gems/cequel-1.1.2/lib/cequel/record/tasks.rb:22:in `block (2 levels) in <top (required)>'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/j/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/j/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/j/.rvm/gems/ruby-2.3.0/bin/rake:23:in `load'
/home/j/.rvm/gems/ruby-2.3.0/bin/rake:23:in `<main>'
/home/j/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/j/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => cequel:migrate
```

**Comment by pezra** [comment]
Rails 5 was unsupported until version 2.0. Can you upgrade and try again.

**Comment by pezra** [comment]
I am closing this but please reopen it if this is still an issue on 2.0.
