### ISSUE TITLE
Errors with Rails 5.2

### ISSUE THREAD

**Issue by erkie** [cequel/cequel#391]
Just upgraded to Rails 5.2 (notably ActiveModel 5.2) and am getting these errors when trying to call `.create` or `.save` on my models. Stack trace at bottom of issue.

I've tracked it down to the fact that it seems that `ActiveModel` now expects the `@attributes` property to be a `ActiveModel::AttributeSet` causing the semantics of checking for `changed?` to save in `attribute_mutation_tracker.rb:45`.

`attributes[attr_name].changed?` throws the nil error because Cequel stores Cequel::Record `@attributes` as a regular hash.

As a quick fix I tried this the following:

```ruby
module ActiveModel
  class AttributeMutationTracker # :nodoc:
    OPTION_NOT_GIVEN = Object.new

    def initialize(attributes)
      @attributes = attributes.is_a?(Hash) ? ActiveModel::AttributeSet.new(attributes) : attributes
```

But that causes the following error:

```
/Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_set.rb:37:in `block in keys': undefined method `initialized?' for #<Cassandra::Uuid:0x00007fc5262f35d0> (NoMethodError)
```

So I'm not sure if `Cassandra::Uuid` might need changing to support ActiveModel 5.2?

Original stack trace (exactly following `MyModel.create`)

```
	17: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:54:in `new'
	16: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:54:in `tap'
	15: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:55:in `block in new'
	14: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/scoped.rb:62:in `initialize_new_record'
	13: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:420:in `initialize_new_record'
	12: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/mass_assignment.rb:39:in `attributes='
	11: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:314:in `attributes='
	10: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:314:in `each_pair'
	 9: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:315:in `block in attributes='
	 8: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:247:in `id='
	 7: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/dirty.rb:66:in `write_attribute'
	 6: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/persistence.rb:327:in `write_attribute'
	 5: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/cequel-3.0.2/lib/cequel/record/properties.rb:384:in `write_attribute'
	 4: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_methods.rb:382:in `id_will_change!'
	 3: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/dirty.rb:312:in `attribute_will_change!'
	 2: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/dirty.rb:174:in `attribute_changed?'
	 1: from /Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/dirty.rb:290:in `changes_include?'
/Users/erik/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_mutation_tracker.rb:45:in `changed?': undefined method `changed?' for nil:NilClass (NoMethodError)
```

My model:

```ruby
class Feed
 include Cequel::Record

  key :id, :uuid
  column :legacy_id, :int
end
```

Code to reproduce:

```
Feed.create({
  "id" => "b0000000-0000-0000-0000-000000000000", 
  "legacy_id"=>388176577
})
```

**Comment by erkie** [comment]
I made this  fork that works. What I did was change the name of the internal instance variable of Cequel to `cequel_attributes` instead of `attributes`. TBH I don't think it's a great solution, as there is probably a simpler approach to connecting `ActiveModel::Dirty` with classes that have `@attributes` instance variables.

https://github.com/feederco/cequel

**Comment by le-doude** [comment]
+1
Having the same issue.

**Comment by pezra** [comment]
I've never tried cequel with rails 5.2. I'd love to have a PR that makes it work, though.

**Comment by erkie** [comment]
@pezra did you check out https://github.com/cequel/cequel/pull/392?

**Comment by erkie** [comment]
@pezra sorry but just wondering what you meant with "I'd love to have a PR that makes it work, though." when there was a PR since before that comment :)

**Comment by baileyspace** [comment]
What's the status on getting the ActiveModel 5.2 support https://github.com/cequel/cequel/pull/378?

**Comment by wflanagan** [comment]
I  think this request is stale, and handled. Will mark as stale and close in 30 days if no one complains.
