### ISSUE TITLE
All attempted hosts failed

### ISSUE THREAD

**Issue by avrusanov** [cequel/cequel#414]
Hello! 

We have strange issue with cequel library.

We have 3 node in the cluster. 

When one cassandra host is down i get error All attempted hosts failed.

After some time from 10 to 100 sec the situation become normal.

But in this range we have unpredictable errors.

With pure datastax cassandra driver the issue is not reproduced.

Cassandra 3.11.1. cequel-3.2.0. cassandra-driver-3.2.3. rails 4.2. ruby 2.4.5

Log:

```
E, [2019-08-15T16:21:29.350736 #13776] ERROR -- : User error: All attempted hosts failed: 10.0.0.12 (Cassandra::Errors::IOError: Connection closed), 10.0.0.14 (Cassandra::Errors::IOError: Not connected), 10.0.0.16 (Cassandra::Errors::IOError: Not connected), params: {"email"=>"anton.rusanov@rcntec.com", "password"=>"xxxxxxxxx", "controller"=>"api/v1/user", "action"=>"get_auth_token"}
E, [2019-08-15T16:21:29.351017 #13776] ERROR -- : Error backtrace: /vendor/bundle/ruby/2.4.0/gems/cassandra-driver-3.2.3/lib/cassandra/future.rb:639:in `get'
/vendor/bundle/ruby/2.4.0/gems/cassandra-driver-3.2.3/lib/cassandra/future.rb:402:in `get'
/vendor/bundle/ruby/2.4.0/gems/cassandra-driver-3.2.3/lib/cassandra/session.rb:177:in `prepare'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/statement.rb:36:in `prepare'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch.rb:64:in `block in apply'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch.rb:64:in `each'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch.rb:64:in `apply'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch_manager.rb:52:in `block in batch'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch_manager.rb:52:in `tap'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/metal/batch_manager.rb:52:in `batch'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/record/callbacks.rb:34:in `save'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/record/validations.rb:53:in `save'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/record/dirty.rb:48:in `save'
/vendor/bundle/ruby/2.4.0/gems/cequel-3.2.0/lib/cequel/record/persistence.rb:207:in `update_attributes'
```

**Comment by wflanagan** [comment]
@avrusanov Is it possible for you to give me an example configuration that shows this problem? You can build it with a docker-compose.  Or, did you resolve the issue?

**Comment by avrusanov** [comment]
Hello! I had resolved the issue .
