### ISSUE TITLE
cequel:migrate errors on Amazon Keyspaces

### ISSUE THREAD

**Issue by jan** [cequel/cequel#420]
`cequel:migrate` uses `client.prepare`, which results in `Cassandra::Errors::InvalidError: unconfigured table foo.participants`. This is the table I want `cequel:migrate` to create.

This is the statement it wants to prepare:

`CREATE TABLE participants ("user_id" uuid, "order_id" uuid, "items" text, "updated_at" timestamp, "created_at" timestamp, PRIMARY KEY ((user_id, order_id)))`

I'm not sure if this is a bug in Cequel or Amazon Keyspaces. Should one be able to prepare a statement on a nonexistant table?

I've patched my local `keyspace.rb` to not prepare statements if they don't have any `bind_vars`, which circumvents the problem.

```
[statement.bind_vars.any? ? prepare_statement(statement) : statement.cql,
                           {arguments: statement.bind_vars}.merge(options)]
```

Log:

```
$ rake cequel:migrate --trace
** Invoke cequel:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute cequel:migrate

rake aborted!
Cassandra::Errors::InvalidError: unconfigured table foo.participants
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cassandra-driver-3.2.5/lib/cassandra/future.rb:637:in `get'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cassandra-driver-3.2.5/lib/cassandra/future.rb:402:in `get'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cassandra-driver-3.2.5/lib/cassandra/session.rb:178:in `prepare'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/metal/keyspace.rb:239:in `block in prepare_statement'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/metal/policy/cassandra_error.rb:47:in `execute_stmt'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/metal/keyspace.rb:238:in `prepare_statement'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/metal/keyspace.rb:211:in `execute_with_options'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/metal/keyspace.rb:194:in `execute'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/schema.rb:100:in `block in synchronize_schema'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/schema.rb:100:in `each'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/schema.rb:100:in `synchronize_schema'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:95:in `block (2 levels) in migrate'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:86:in `each'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:86:in `block in migrate'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:73:in `each'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:73:in `migrate'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cequel-3.2.1/lib/cequel/record/tasks.rb:39:in `block (2 levels) in <main>'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/jan/.rbenv/versions/2.7.2/bin/rake:23:in `load'
/Users/jan/.rbenv/versions/2.7.2/bin/rake:23:in `<main>'
Tasks: TOP => cequel:migrate
```

Environment

- `cequel (3.2.1)`
- `cassandra-driver (3.2.5)`
- `ione (1.2.4)`
- `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`
- Documentation claims that Amazon is running Cassandra `3.11.2`.
- The cluster object says `protocol_version=4`.

**Comment by RajatGoyal** [comment]
what does your cequel.yml look like?
